linters:
  enable-all: true
  disable:
    - exhaustivestruct # not revelent
    - gochecknoglobals
    - goerr113 # too strict
    - golint # deprecated
    - interfacer # deprecated
    - ireturn # not revelent
    - maligned # deprecated
    - scopelint # deprecated
    - tagliatelle # breaking
    - testpackage # too strict
    - varnamelen # not revelent
    - wrapcheck # too strict
    - gomnd # too strict

issues:
  exclude-rules:
    - path: main.go
      text: bad syntax for struct tag pair
    - path: main.go
      text: Expected 'a', Found 'c'
    - path: main.go # FIXME
      text: Function 'main' is too long
    - path: (.+)_test.go
      linters:
        - typecheck
    - path: metrics/prometheus/prometheus.go # FIXME
      text: counter metrics should have "_total" suffix

linters-settings:
  forbidigo:
    forbid:
      - '^print(ln)?$'
