builds:
  -
    goos:
      - freebsd
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm
      - arm64
      - 386
    goarm:
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: 386
      - goos: windows
        goarch: arm

archives:
  -
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
