'# Commented YAML Lines':
  - '# name: test'
  - '# description: test'
source:
  Github:
    - token: dskjdslk
      user: mritsurgeon
      filter: {}
destination:
  Localpath:
    - path: /backup
      keep: '10'
cron: 0 00 12 ? * Monday
